# Generated by Django 3.2.4 on 2023-11-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='mysql_list', to='dcmdb.Project', verbose_name='项目'),
        ),
    ]
