apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: dummy
    app.kubernetes.io/part-of: admission-webhook-example
    app.kubernetes.io/managed-by: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 10Mi
            cpu: 10m
          requests:
            memory: 10Mi
            cpu: 10m
