# Generated by Django 3.2.4 on 2023-11-27 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('create_at', models.IntegerField(default=public.models.base.now_ts, verbose_name='创建时间')),
                ('update_at', models.IntegerField(default=public.models.base.now_ts, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='云厂名称')),
                ('desc', models.CharField(max_length=255, verbose_name='云厂描述')),
                ('access_id', models.CharField(max_length=255, verbose_name='AccessID')),
                ('access_key', models.CharField(max_length=255, verbose_name='AccessKey')),
            ],
            options={
                'verbose_name_plural': '云厂商',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('create_at', models.IntegerField(default=public.models.base.now_ts, verbose_name='创建时间')),
                ('update_at', models.IntegerField(default=public.models.base.now_ts, verbose_name='更新时间')),
                ('name', models.CharField(default='', max_length=255, verbose_name='产品名称')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='产品描述')),
            ],
            options={
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('create_at', models.IntegerField(default=public.models.base.now_ts, verbose_name='创建时间')),
                ('update_at', models.IntegerField(default=public.models.base.now_ts, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='用户组名称')),
                ('desc', models.CharField(max_length=255, null=True, verbose_name='用户组描述')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugadmin', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('users', models.ManyToManyField(related_name='usergroup', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name_plural': '用户分组',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('create_at', models.IntegerField(default=public.models.base.now_ts, verbose_name='创建时间')),
                ('update_at', models.IntegerField(default=public.models.base.now_ts, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='项目描述')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name_plural': '项目',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.usergroup', verbose_name='用户组'),
        ),
    ]
